### ISSUE TITLE
Public access to Whole Tale

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#121]
For discussion

Initial thoughts:
* Unauthenticated user can access Whole Tale dashboard 
  * View Public Tales
  * Browse and download files
  * ... anything a read-only user can do on a tale and public tales
* Gravatar is replaced with Sign-in link when not signed in
* Anything the user wants to do that requires authentication requires sign-in
* Need to move Terms of Use and acknowledgements someplace else

**Comment by bodom0015** [comment]
Looking over the existing code, the current "Public Tales" view ties in rather with authenticated resources:
* Instances are used to render the "Running Tales" section
* User profile used to render the navbar
* Start/Stop buttons obviously wouldn't work either

This code is rather tightly coupled with the other Tale Catalog pages (the other two views inherit this), so that makes it a bit harder to change it by itself. For example, the MyTalesComponent subclass only overrides the HTML and ends up inheriting all of the methods of `PublicTalesComponent`: https://github.com/whole-tale/ngx-dashboard/blob/master/src/app/%2Btale-catalog/tale-catalog/components/my-tales/my-tales.component.ts

Would it be acceptable to instead build up a new view using existing components from the UI? This way, we hopefully don't have to change as many of the long-term assumptions about these views.

**Comment by craig-willis** [comment]
I have no objections to a separate view for the unauthenticated "public tales" view. I assume this would be the same for the run view?  I think we'd want an unauthenticated user to access the run view, view metadata, browse and download files/versions/runs, etc. Would we need separate view(s) for these as well?

**Comment by bodom0015** [comment]
Hmmm.. yes probably, and you bring up an excellent point - duplicating both set of views would be quite a lot of UI to try to recreate. I know that for a few things (e.g. rendered read-only metadata) we have some special components that can handle that, as well as the file-browser which would be reusable as well.

Sorry for waffling a bit on this, but I will go back and see if I can figure out a workable pattern here

**Comment by craig-willis** [comment]
Fixed by https://github.com/whole-tale/ngx-dashboard/pull/277
