### ISSUE TITLE
Cannot install pygraphviz library in Jupyter Notebook environment.

### ISSUE THREAD

**Issue by sahil1105** [whole-tale/whole-tale#44]
Hi, I was trying to install my package PW_explorer as follows:
`pip install PW_explorer`
which has a dependency on graphviz and pygraphviz.
But I get the following error which I wasn't able to resolve:

[whole_tale_msg_error.txt](https://github.com/whole-tale/whole-tale/files/2451943/whole_tale_msg_error.txt)

Any thoughts?

**Comment by Xarthisius** [comment]
Hi @sahil1105, thanks for your bug report! Unfortunately this issue is not Whole Tale specific. I can reproduce your error just by running `pip install PW_explorer` in a vanilla jupyter notebook in a docker container. Please refer to the suggestion in the error message about how to install GraphViz (you may want to check conda packages too).
