### ISSUE TITLE
Provide dev Dataverse deployment

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#49]
Bring up and document process for deploying Dataverse based on latest docker compose process https://github.com/IQSS/dataverse-docker. We will also need a dev version of the installation list https://services.dataverse.harvard.edu/miniverse/map/installations-json that includes our dev instances. Ideally with some bootstrapped data. This instance will be used for the external tools integration testing.

**Comment by poikilotherm** [comment]
Maybe my work on https://github.com/IQSS/dataverse/issues/5292 is helpfull?

**Comment by pdurbin** [comment]
@craig-willis hi! You are very welcome to develop against https://demo.dataverse.org if you don't want to install Dataverse yourself. Please feel free to hop in http://chat.dataverse.org sometime if you want to discuss deployment options with me @poikilotherm and others!

dataverse-docker is the brainchild of @4tikhonov so I pinged him at https://github.com/IQSS/dataverse-docker/issues/8#issuecomment-438274747

**Comment by craig-willis** [comment]
Thank you @pdurbin. Just making a few notes based on our discussion on http://chat.dataverse.org.

Perhaps the easiest path  would be to [have our external tool added to dev1.dataverse.org](http://irclog.iq.harvard.edu/dataverse/2018-11-13#i_78612). This means we wouldn't need to install Dataverse, but I'm still interested/somewhat invested in testing out the docker deploy process.

I also asked about [exemplar datasets](http://irclog.iq.harvard.edu/dataverse/2018-11-13#i_78627) that we could use to test our integration.  You mentioned:
* A similar question asked to the [Dataverse community](https://groups.google.com/d/msg/dataverse-community/N96j20ypepc/RiY6rExFGQAJ) during the Whole Tale workshop! There are a few examples of datasets with large numbers of downloads (but in some cases because of lots of files).
* Another related to a [2017 news story](https://www.theverge.com/2017/1/4/14158048/deep-space-fast-radio-wave-burst-frb-121101). The data https://doi.org/10.7910/DVN/QSWJE6 is audio/MP3.
* And perhaps the most fruitful was the [American Journal of Political Science](https://dataverse.harvard.edu/dataverse/ajps) with an [example dataset](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/GSQG1K).

**Comment by 4tikhonov** [comment]
@craig-willis please be aware that Datacite has changed its policy and from some time ago it's not possible to publish datasets without getting account there, even for tests. We're switching back to EZID to get environment for development.

**Comment by craig-willis** [comment]
@pdurbin @4tikhonov @poikilotherm  -- thank you for your input on this issue.  I'm now reading through https://github.com/IQSS/dataverse/issues/4665 trying to understand the current state of Docker support in the Dataverse community.  Note that as I'm working through this process, I'm also hoping to replace my very stale work on https://github.com/nds-org/ndslabs-dataverse/ (https://github.com/nds-org/ndslabs-dataverse/issues/8) which is related to https://github.com/IQSS/dataverse-docker/issues/8.

**Comment by pdurbin** [comment]
@craig-willis that issue is quite long but I hope this comment about the history of Dataverse's use of Docker (in which you play a starring role!) helps: https://github.com/IQSS/dataverse/issues/4665#issuecomment-391926503

You might also want to read http://guides.dataverse.org/en/4.9.4/developers/containers.html#docker

With regard to NDS Labs Workbench, it was great to chat with you in Chicago about it and I'd love for you to take a look at https://github.com/IQSS/dataverse/issues/4152 when you have a chance because I'd love feedback on what's currently in the guides (see http://guides.dataverse.org/en/4.9.4/installation/prep.html#nds-labs-workbench-for-testing-only ) and if an update is in order, a pull request would be quite welcome.

My personal use of Docker in Dataverse-land mostly involves using "docker-aio" to run our integration test suite ( http://guides.dataverse.org/en/4.9.4/developers/testing.html#running-the-full-api-test-suite-using-docker ) from time to time (maybe a couple times a month) on my laptop, especially if tests start failing on the main server where we run integration tests ("phoenix", see http://guides.dataverse.org/en/4.9.4/developers/testing.html#the-phoenix-server ). I'm not opposed to using Docker more but it hasn't been a priority for me.

**Comment by craig-willis** [comment]
Thank you @pdurbin.  I put my response to this in https://github.com/IQSS/dataverse/issues/4665#issuecomment-439450722, since it seemed most appropriate.  Sorry for dropping the ball on https://github.com/IQSS/dataverse/issues/4152, but I will indeed give it some attention.

**Comment by craig-willis** [comment]
Closing this dormant issue.  In the end we never deployed Dataverse ourselves and relied on dev and demo (https://demo.dataverse.org/) instances and collaboration with the Harvard team.
