### ISSUE TITLE
repo2docker integration discussion

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#52]
As we've looked into integrating with repo2docker, three points have come up:

1) We'd like the ability to change the base image or, perhaps more useful, to parameterize the template
2) We need a way to store the repo2docker version so we know which version to use (and possibly template) to generate an image from a Tale/repo ala https://github.com/jupyter/repo2docker/issues/170#issuecomment-356482270
3) Using an `/environment` directory  ala https://github.com/jupyter/repo2docker/issues/386

On the topic of changing the base image, we have two different motivations. 

1. WT doesn't require Jupyter in all images (we don't use JupyterHub today).  For example, we run Rstudio directly and envision doing the same for other environments, although admittedly they'll be edge cases as our primary cases are covered by Jupyter/Rstudio today. 
2. We have at this point primarily anecdotal evidence of communities that need non-Ubuntu base operating systems. The Dark Energy Survey (DES) and LSST projects have most of their tools packaged for CentOS. From the last [WT OSI WG call](https://github.com/whole-tale/whole-tale/issues/50), it's my understanding that the Neurodebian packages eventually find their way to Ubuntu, but there's often a delay.  

In the first case, we would want to change the template but not necessarily  the base OS.  In the second, we might want to change the base OS and eventually add things like buildpacks for yum.txt. This may open a Pandora's box.

Pinning the repo2docker version and supporting the `/environment` subdirectory seem less controversial.

**Comment by craig-willis** [comment]
We've started the process of integrating `repo2docker` into Whole Tale platform for image customization.  The primary rationale is that we can leverage and contribute to an existing project instead of developing something that would end up being quite similar in the end.

One of the broader issues we've encountered is RStudio support. For example:
* It's not possible to have [RStudio be the default application on an empty repo/workspace](https://discourse.jupyter.org/t/rstudio-or-openrefine-as-default-interactive-application-on-empty-repo/325)
* While it is possible to run RStudio from `repo2docker`, the built image still uses the [Jupyter PORT and CMD](https://github.com/jupyter/repo2docker/issues/533#issuecomment-451689268)
* Today, Whole Tale leverages the `rocker/geospatial` images, while `repo2docker` assumes an Ubuntu base then installs  rstudio-server and shiny-server via buildpack. The only Binder [example that uses rocker images](https://github.com/binder-examples/rocker/blob/master/Dockerfile) requires a Dockerfile
* If we allowed specifying an alternative base image, we'd likely run into problems with versioning strategies.  For example, `repo2docker` allows the user to change the runtime, while the runtime is baked into the `rocker` images.

For us, primary benefit of using `repo2docker` is the templated customization. Users can extend the environment without needing to know how to write a Dockerfile.  Another benefit is that Tales in Whole Tale will be compatible with Binders. I can push my Tale to Github or import my Binder to Whole Tale.  

Are there any existing initiatives to bridge these two worlds? Is it worth WT pursuing?

@cboettig I wonder if you have any thoughts one this.

**Comment by cboettig** [comment]
Hi @craig-willis , these are good questions and not sure there are any easy answers, though @choldgraf, @yuvipanda and co will very likely have better answers than me.  


Like you say, it would be possible for WT to parse  the templated customization (I think by this you mean files like `requirements.txt` and `apt.txt` to customize the install?) without actually building on the same images.  That would likely work most of the time and create really hard-to-debug problems for those rarer instances where getting the same package from different upstream sources causes problems. 

I recently tried reconstructing a project from the deep past of 2015 (aka prior to rocker versioned stack; though of course this being science most of the code base was a year or two older).  Picking the MRAN date to match reliably got me viable versions of the R packages needed, but I had to track down and compile the right versions of JAGS, pandoc, and pandoc-citeproc (the latter two obviously only relevant for the output and not the computation) onto a versioned image before things would build (see [Dockerfile](https://github.com/cboettig/nonparametric-bayes/blob/095252d40632304f2c3e1da1294d3db356f872d3/manuscripts/Dockerfile).  I raise this example because it highlights a few lessons for me: `apt.txt` wouldn't cut it, as debian:jessie, debian:stretch, ubuntu:16.04, etc ship different versions of these things.  but also that regardless of the base platform of the containerized system, as the user I still have to do this similar translation from whatever my native environment was, and that is often the hardest part (particularly in the past). so this is always something of a problem unless you're developing on the containerized system or something very close to it...


- Regarding the default application, since that can be toggled in the link structure used to launch the image, (the `?rstudio`) -- not sure if that's sufficient for WT use?

As far as interoperability is concerned, I do get that most scientists don't want to write Dockerfiles, but I'm still hesitant about alternative strategies for fancy customization. I suspect the majority of use cases are simple scripts that can be run out of the box without anything special, or extended using existing language-specific standards & packaging mechanisms (DESCRIPTIONs, requirements.txt / setup.py, gemspec, etc).  but that's also my bias

**Comment by craig-willis** [comment]
Thanks for the great feedback, @cboettig.  I should've acknowledged that Binder team has certainly been very supportive in helping us work through some of these issues.   As I'm working to replace our base `rocker/geospatial` base image with `repo2docker` I guess I'm coming to terms with what we might lose in the transition.

**Comment by cboettig** [comment]
@craig-willis I think you've already nailed it in that the main risk is that some things that work in a `rocker/geospatial` stack aren't going to work on repo2docker's `ubuntu` based images.  

Copying over things from the rocker stack will help that (e.g. libs installed in both `geospatial` and `verse`); but of course some versions of libs might be different that way and that could break things that worked on rocker/geospatial. (binder is ubuntu:18.04 based by default now?  What's binder's model for when to update LTS? at the time of the new LTS release or not until the old one reaches end of life?  How do I indicate which binder image/ LTS release I want?)   My more general concern is that it feels less obvious to me what is in the binder stack and how test and debug it locally.

**Comment by craig-willis** [comment]
Thanks again, @cboettig.

I'm thinking that we could continue supporting the `rocker` base images -- either via `repo2docker`'s explicit Dockerfile method or even via our original build mechanism.  If the rocker images are intended to be extended via Docker, then maybe the community will be comfortable with this approach.  We can use the basic `repo2docker` model for our other users that need simple Rstudio with a handful of packages.  

I don't have answers to all of your questions and would be interested to hear how the decisions are made for rocker.  They have moved to 18.04 and I expect they would move to the new LTS close to when it's released.  I'm actively working on adding the ability for a repo to pin to a particular repo2docker version, which determines the LTS version.  

> My more general concern is that it feels less obvious to me what is in the binder stack and how test and debug it locally.

It does require the leap to accept `repo2docker` instead of Docker and some of the assumptions that come with it.  I've advocated for WT to adopt it as a component with the hope of benefitting from many reproducibility-minded folks working in the same space.

**Comment by choldgraf** [comment]
might also be worth looping in @karthik, who has also been working on finding more friendly ways to support repo2docker (well, Binder really) in the R community. If I recall, he wrote a little tool that constructs binder-ready Dockerfiles from R repositories. In a sense that circumvents what repo2docker is doing, but it might be a nice way to keep technical development overlapping.

re: LTS etc, @cboettig that is a great question. the repo2docker/binder communities are still figuring out how far to push on reproducibility features in the longer-longer term. It would be great if you could provide your thoughts on what sounds reasonable!

**Comment by craig-willis** [comment]
Thanks @choldgraf.  

One of our initial plans was to to make the `repo2docker` template configurable.  We abandoned this idea since it seemed like most use cases could be supported with the current template. (On one of the community calls, I think we discussed supporting this type of extension not through templates but through the buildpack mechanism). In light of the rocker case, I wonder if this is worth revisiting. Looking at https://github.com/bocinsky/guedesbocinsky2018 as a recent example, it seems like it would be useful to be able to simply add an `apt.txt` and `install.R` to this repo and declare that they're basing this on a rocker-geospatial template/buildpack (and therefore `debian:stretch` instead of `buildpack-deps:bionic`).

**Comment by choldgraf** [comment]
yeah, this still feels compelling to me...not sure what the broader repo2docker consensus is around this topic. Perhaps it's worth making a specific proposal around that we can discuss as a group? Something with enough meat on it that we can discuss pros, cons, etc?

I'd love to hear @cboettig's thoughts on this as well! :-)

**Comment by craig-willis** [comment]
I've been working on a proof-of-concept and will gladly write something up and circulate for comment.   As I recall, those on the call were open to the idea, but we didn't have a compelling example -- I just didn't realize that it was under my nose!

**Comment by craig-willis** [comment]
Connecting this to @choldgraf's original thread about making the base image configurable:

https://github.com/jupyter/repo2docker/issues/487

I think the discussion of potentially adding Rocker support to repo2docker should go there.

**Comment by craig-willis** [comment]
This integration was completed in 2019 (see  https://github.com/whole-tale/gwvolman/pull/43). We currently maintain our own fork of r2d (https://github.com/whole-tale/repo2docker) and plugin (https://github.com/whole-tale/repo2docker_wholetale/) that includes support for Rocker, MATLAB and STATA environments.
