### ISSUE TITLE
Download all files from a Dataverse dataset based on launching Whole Tale from one of the files.

### ISSUE THREAD

**Issue by pdurbin** [whole-tale/whole-tale#66]
I have a replication dataset at https://github.com/pdurbin/dataverse-irc-metrics that I have working with MyBinder and I sometimes import into Dataverse (just dev servers for now). It looks like this:

![Screen Shot 2019-06-11 at 4 34 04 PM](https://user-images.githubusercontent.com/21006/59304709-ca4b5c00-8c66-11e9-825b-2068132b7236.png)

From Dataverse I'd like to click "Explore" and then "Whole Tale" on a Jupyter Notebook like this...

![Screen Shot 2019-06-11 at 4 04 33 PM](https://user-images.githubusercontent.com/21006/59304068-8c9a0380-8c65-11e9-92e2-273f60df82e8.png)

... and execute that Jupyter Notebook in Whole Tale.

Right now in Whole Tale I only see the one file that I clicked:

![Screen Shot 2019-06-11 at 4 07 55 PM](https://user-images.githubusercontent.com/21006/59304175-b521fd80-8c65-11e9-82bf-8a559262e20f.png)

In Whole Tale Slack I suggested to @Xarthisius that perhaps as a workaround until Dataverse external tools (like Whole Tale) are supported at the dataset level (see https://github.com/IQSS/dataverse/issues/5028 ), Whole Tale could download all the files for that dataset based on a single file. He said to go ahead and create this issue and I'm very happy to help explain what needs to be done. In short it should be something like this:

- Based on the ID of the file in Dataverse, figure out the DOI or Handle (collectively called Persistent ID or PID) of the parent dataset.
- Download a JSON or XML representation of the dataset that has all the file database IDs.
- Put all the file IDs together separated by commas and feed it into the Dataverse "Data Access" API like this: https://demo.dataverse.org/api/access/datafiles/307909,307910,307908?gbrecs=true . Docs at http://guides.dataverse.org/en/4.14/api/dataaccess.html#multiple-file-bundle-download

I believe the concept of downloading all files based on the DOI of a dataset has already been implemented. There are docs at https://wholetale.readthedocs.io/en/stable/users_guide/manage.html that we link to from http://guides.dataverse.org/en/4.14/admin/integrations.html#whole-tale and that look like this:

![Screen Shot 2019-06-11 at 4 36 42 PM](https://user-images.githubusercontent.com/21006/59304970-3fb72c80-8c67-11e9-88a4-abbdb3314832.png)
 
So it might be that the only thing you need is how to find the parent DOI of the dataset based on the file.

Given 3371438 from https://dataverse.harvard.edu/file.xhtml?fileId=3371438 one way to discover the DOI of the parent dataset is like this:

`curl -s https://dataverse.harvard.edu/api/search?q=identifier:3371438 | jq -r '.data.items[0].dataset_persistent_id'`

doi:10.7910/DVN/TJCLKP

Here's a screenshot of the same idea in a browser:

![Screen Shot 2019-06-11 at 4 41 51 PM](https://user-images.githubusercontent.com/21006/59305249-dd126080-8c67-11e9-8a6b-0a5456a2ac91.png)

**Comment by craig-willis** [comment]
Thanks, @pdurbin. I'm excite to see progress on this.

In addition to your request to downloading all files based on one of the files, there is another finer point we're going to need to work out.

Every "tale" in Whole Tale has two primary folders: one for external data and the other we call the tale "workspace". A fundamental part of our design is that data imported from external sources, such as Dataverse, is immutable and therefore read-only. This ends up in the "data" folder with the expectation that your code that operates on that data is in the "workspace" and produces derived datasets or analytical results in the workspace. The case you're describing here seems to be better suited by the data package being brought into the "workspace", where the user has read/write capabilities in the notebook.  In our latest version, repo2docker runs on the "workspace".

If we implement the suggested change, the data package would end up in the "data" directory (readonly) with the workspace empty. This isn't likely what you were expecting.

In the future, if a "tale" were published to Dataverse, we would want to import it as such. One option might be for us to detect that this is a repo2docker compatible data package and treat it as a "tale" on import bringing the files into the workspace, which would require additional changes and would merit further discussion.

**Comment by pdurbin** [comment]
@craig-willis ok. I think I understand. At a high level there is a lot of interest in the Dataverse community in a workflow like this:

- I'm looking at a dataset in an installation of Dataverse.
- I click a button called "Compute"  or "Exectute Code" or similar.
- I am brought into an environment such as Whole Tale where I can run the code I was looking at in Dataverse and perhaps make some modifications to that code.

It sounds like we're not quite there yet. I wonder if describing the Whole Tale external tool with "Dataverse users can launch Jupyter and RStudio environments to analyze published datasets" at http://guides.dataverse.org/en/4.14/installation/external-tools.html is a bit too optimistic. Maybe it was just wishful thinking on my part. 😄  Like you said, it sounds like there are still some details to work out. I still think Whole Tale needs all the files in the dataset though, especially if you want to run repo2docker on them. So maybe this issue represents the next step? And then we can think more about data vs. workspace later? Or as part of this issue? Whatever you prefer. 😄

**Comment by craig-willis** [comment]
Thanks, @pdurbin.

>I wonder if describing the Whole Tale external tool with "Dataverse users can launch Jupyter and RStudio environments to analyze published datasets" at http://guides.dataverse.org/en/4.14/installation/external-tools.html is a bit too optimistic.

There is a distinction between launching Jupyter and Rstudio environments to analyze published datasets, which we do support, and launching a customized environment with repo2docker configuration files to run a Jupyter notebook or R script included in the package.  The first we support (don't we?) but the second not yet.

I wanted to elaborate a bit on the "external data" capability in Whole Tale, as it's one that may be of interest to Dataverse and we'd welcome your feedback on. I'd also like to bring your attention to our nascent [Tale format specification](https://docs.google.com/document/d/11mHpqByI1odaRydoz3mSdXZQ6eBwg1JVzPfcCKejyO4).

Consider the following example:

The replication package [Replication Data for: The Hostile Audience: The Effect of Access to Broadband Internet on Partisan Affect](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/W1YJZQ) contains a file called `bbindex.csv` used to create Figure 1 in the paper. According to a footnote, the file was downloaded from the FCC website http://transition.fcc.gov/wcb/iatd/comp.html. Browsing to the FCC site, you can see multiple versions of that dataset. Which version was used?  Has it been modified in any way? What if this was part of another dataset published in Dataverse or ICSPR, how do we encourage proper citation and attribution?  Had the researcher created the replication package in Whole Tale and registered the source dataset, we would have an explicit reference to the original version and, since we treat it as read only, have some confidence that it wasn't modified in any way before use.  If they created a "tale" and published it back to Dataverse, we can also ensure that the source dataset is properly cited and credited.

With our current "external tools" integration, we treat Dataverse datasets as external data, which means they are considered immutable and brought into the "data" directory instead of the "workspace" (which contains code, repo2docker configuration etc).

However, as you've noted the expectation changes when the published dataset contains code and data as above -- is a published "tale" or "binder". Now the expectation is that the "dataset" be treated not as input data, but as an executable environment where the user would need read-write access to run code/notebooks and generate outputs.

In our current integration with DataONE, we publish using our [tale format](https://docs.google.com/document/d/11mHpqByI1odaRydoz3mSdXZQ6eBwg1JVzPfcCKejyO4/edit)  -- based on [BagIt-RO work](https://github.com/ResearchObject/bagit-ro/) -- which includes a `manifest.json` file that allows us to determine that this is indeed a tale, keeps track if cited datasets,  and, among other things, allows us to reconstruct a filesystem hierarchy from a system that requires a flat organization. You can see a very basic example here: doi:10.5063/F1VD6WSP.  But this is a tale, not a binder or non-binder AJPS replication package. We've also created a [demonstration video](https://drive.google.com/file/d/1tkTWoDo5X8oTNfki9B2oq-tWcDrjSwEJ/) that shows how this works for both export and publishing to DataONE.

Admittedly, the average researcher may not fully understand the value of our external data approach, but I would hope that data repositories do.  The "tale format" is something we're starting putting forward, but is obviously not part of the Binder/repo2docker framework. And finally, we're certainly interested in supporting the case you've described: running non-tale binder/replication package/research compendium/capsules, but we don't (yet) have a way of detecting that these should be treated differently than other Dataverse datasets.

**Comment by pdurbin** [comment]
@craig-willis hi! I popped in here to say that for the "find a dataset based on its file ID" method I mentioned above that instead of...

`curl https://dataverse.harvard.edu/api/search?q=identifier:3371438`

... the following might be slightly better or more future proof:

`curl https://dataverse.harvard.edu/api/search?q=entityId:3371438`

But either one is fine.

@Xarthisius mentioned some work going on in https://github.com/whole-tale/girder_wholetale/pull/317 which is great! Thank you!!

**Comment by craig-willis** [comment]
Thanks, @pdurbin.   Sorry for the long comment yesterday, but I do think it's important that we're on the same page about some of the design assumptions in Whole Tale w.r.t. Dataverse integration. It may seem out of scope for this issue, but what you're really asking for in the description is the ability to run a Binder-compatible replication-package published to Dataverse in Whole Tale (hence https://github.com/whole-tale/girder_wholetale/pull/317).

**Comment by craig-willis** [comment]
@pdurbin We've deployed a preliminary version (proof-of-concept) of this to https://dashboard.stage.wholetale.org (thank you @Xarthisius).

This includes the following:
* Downloads all files from dataset based on launching WT on one file
* Adds the "Import as Tale" toggle to bring the dataset contents into the workspace (needed for repo2docker to build the image)
* Adds a "Jupyter with R" base environment

Using the external tools integration, you should be brought to the "Compose" page to select the desired base environment (in your case "Jupyter with R"). Selecting "Import as Tale" will pull things into the workspace and repo2docker will run during launch:

<img width="1371" alt="Screen Shot 2019-06-17 at 9 20 13 PM" src="https://user-images.githubusercontent.com/4334350/59646622-bfe90080-9145-11e9-95a5-f773169339c0.png">

Clicking "Launch Tale" will build the image and take you to the Run page with the built environment:

<img width="1375" alt="Screen Shot 2019-06-17 at 9 22 05 PM" src="https://user-images.githubusercontent.com/4334350/59646693-fde62480-9145-11e9-93f1-5a3014e07064.png">

Note that this doesn't yet include https://github.com/whole-tale/girder_wholetale/pull/319, so there is no `data` directory for `irclog.tsv`. I added a `dir.create("data")` prior to the download in your notebook and it seems to work.  

Feedback welcome.

**Comment by craig-willis** [comment]
@pdurbin Follow-on question when you have a minute.   In https://github.com/whole-tale/girder_wholetale/pull/319 we're retrieving the full folder hierarchy when present.

In your example https://dev2.dataverse.org/dataset.xhtml?persistentId=doi:10.5072/FK2/NYNHAM, the path starts with `dataverse-irc-metrics-8f0b5b505de7730ebd9d57439952542a66a6bae0/` because you apparently downloaded the zipfile for a particular Github commit and uploaded to Dataverse. The repo2docker configuration is in this subdirectory.  In this case we'd like to strip that first path element when importing.

In the [repo2docker Zenodo provider](https://github.com/jupyter/repo2docker/blob/master/repo2docker/contentproviders/zenodo.py),  they use a heuristic to try to determine whether to ignore the first path element when building the image. If the downloaded dataset as "upload_type=software" and there's only one file (i.e., a zipfile), then strip that first path element after unzipping.

Do you have any thoughts how we should handle this with Dataverse?  The user could upload a zipped Github repo as you did; manually upload repo2docker config files into a dataset; or even upload a zipped zipfile.

**Comment by pdurbin** [comment]
@craig-willis @Xarthisius @matthewturk thanks for all the help this morning.

I guess I'm a little confused why there's a "data" directory in Dataverse with the "irclog.tsv" I want...

<img width="540" alt="Screen Shot 2019-06-21 at 12 39 30 PM" src="https://user-images.githubusercontent.com/21006/59937938-b996a500-9421-11e9-9e52-d896155bbfc8.png">

... but on the Whole Tale side there is no "data" directory and no "irclog.tsv" file...

<img width="898" alt="Screen Shot 2019-06-21 at 12 39 14 PM" src="https://user-images.githubusercontent.com/21006/59938003-dd59eb00-9421-11e9-8e1f-33e636b6cab9.png">

I'm excited that most of the files have been brought over and I have a line in my Jupyter notebook to download the irclog.tsv from my server but am I missing something? Why is there no "data" folder with the "irclog.tsv" file in it.

It's almost lunch time here at #dataverse2019 and no worries about replying right away. We can talk this out next week or whenever. If I do try to demo this stuff instead of giving my planned talk, I'll just use my workaround of downloading "irclog.tsv" from my server by executing the appropriate line in my Jupyter Notebook.

@craig-willis I don't think I answered any of your questions above. When I catch my breath, I will. 😄 

Thank you to all! 🎉

**Comment by Xarthisius** [comment]
@pdurbin it's because https://github.com/whole-tale/girder_wholetale/pull/319 was not merge there when dataset was first imported, but notice that there's `irclog.tsv` in there, just not in the `data/`

**Comment by pdurbin** [comment]
> but notice that there's `irclog.tsv` in there, just not in the `data/`

Oh! Duh! Thanks, @Xarthisius! I was blind to it. 🎉

**Comment by pdurbin** [comment]
This is done, right? I mean, I demo'ed this half a year ago in my crazy ideas talk: https://scholar.harvard.edu/pdurbin/blog/2019/jupyter-notebooks-and-crazy-ideas-for-dataverse

Besides, these days Dataverse supports launching Whole Tale from a dataset page. In fact, we just enabled it on our demo site: https://github.com/IQSS/dataverse/issues/6446

Closing.
