### ISSUE TITLE
Vocabulary hosting service

### ISSUE THREAD

**Issue by craig-willis** [whole-tale/whole-tale#95]
**Problem**:
We are developing new RDF vocabularies (https://github.com/whole-tale/serialization-format/pull/2, https://github.com/whole-tale/whole-tale/issues/89) and will need a place to host them. We have decided on https://vocabularies.wholetale.org/wt/1.0/ for the initial terms.

**Approach**:
* Specify a repository to house all vocabularies going forward (e.g., https://github.com/whole-tale/serialization-format/)
* Configure repo to use gh-pages to host vocab files
* Configure Github Action to call `pyLODE` to auto-generate HTML based on ttl
* Change `deploy-dev` and `terraform_deployment` traefik configuration to route all requests to a github-pages site

**Status**:
* [x] Configure gh-pages, GHA (see https://whole-tale.github.io/serialization-format/wt/1.0/) 
* [x] Update deploy-dev https://github.com/whole-tale/deploy-dev/pull/46
* [x] Update terraform_deployment https://github.com/whole-tale/terraform_deployment/pull/47

(Note: part of my wants to move the vocabularies and related docs out of the `serialization-format` repo and into something dedicated to vocabs.)

**Comment by mbjones** [comment]
+1 on formalizing all of this. Two quick points to consider:

- I think an important part is to ensure that the namespace URI will continue to resolve (even if a project ends), so it would be good to use an indirect URI space for the vocabulary namespace that can be relocated under new management, or under an open source maintainer
- it is helpful if community vocabularies are visible in community vocabulary serverrs. We publish our vocabularies to two common ontology repositories, BioPortal (e.g., see [ECSO](https://bioportal.bioontology.org/ontologies/ECSO) there) and the ESIP Community Ontology Repository (COR) (e.g. see [ProvONE](http://cor.esipfed.org/ont?iri=http://purl.dataone.org/provone/2015/01/15/ontology%23) there). Both of these provide ways to visualize and browse the ontology classes -- COR uses pyLode like you are proposing, so that would probably be a very easy way to get the functions you want without having to maintain another service ourselves. The OBO Foundry would be another good choice, but there are curation constraints on that one that might be a barrier.

**Comment by craig-willis** [comment]
For the record, the discussion of the namespace URI was part of https://github.com/whole-tale/serialization-format/pull/2.

Regardless, I'm open to registering a purl, if that's the suggestion. I assume purl.org would suffice?  The choice then is whether to redirect to COR with the URL for the RDF version of our vocabulary in Github or to just redirect to gh-pages as is currently implemented.

Looking at https://purl.dataone.org/, I gather that DataONE runs its own purl service and, at least for more recent vocabularies, redirects are to raw Github content (e.g.,  https://purl.dataone.org/collections-1.1.0, https://purl.dataone.org/portals-1.1.0). These don't (yet) appear to be registered with COR (why?) 

Registering the vocabulary with COR seems easy enough -- assuming it's welcome -- but it adds another maintenance step if the vocabulary is updated.  It would give us pyLODE rendering "for free" (by depending on an external service).

On the other hand, running pyLODE via GHA means that the vocabulary and its rendering(s) are available directly in the Github repo.

**Comment by mbjones** [comment]
I think purl.org would be fine, although it had some maintenance issues a few years back where they all stopped resolving for about 6 months due to a lack of a maintainer. That incident spawned https://w3id.org/ and other resolvers. We put up purl.dataone.org as a simple redirector for namespaces we are maintaining. I'm not sure if that was a good idea. Maybe we'll know in 10 years. Some of those are for vocabularies, some are for other documentation sites. We could use more consistency in how we handle namespaces, but like all things, it has grown a bit organically.

COR is open to new vocabularies as far as I can tell. I'm unsure of its lifespan. BioPortal has been stable for a very long time. We consider both of them simple vocab visualization and search services, so not fundamentally critical if they get moved down the line.

+1 on rendering pyLode on the github repo -- that sounds pretty good too.

**Comment by craig-willis** [comment]
For this release, we went with the approach in the description:

* Github pages + GHA that builds docs using pyLode https://whole-tale.github.io/serialization-format/wt/1.0/
* Proxied route from vocabularies.wholetale.org (see https://github.com/whole-tale/deploy-dev/pull/46/files)
